### ISSUE TITLE
WSAFile format is written incorrectly

### ISSUE THREAD

**Issue by OmniBlade** [ultraq/redhorizon#4]
The field you have as an int for Delta is an unsigned short follow by another unsigned short which is either 0 (no palette) or 1(palette included). Delta is also calculated incorrectly, it should be set to the size of the largest format40 encoded frame +37 for CNC style ones and +33 for Dune2 style ones. The current code would be hit or miss if a WSA written with it worked in game.

**Comment by ultraq** [comment]
Thanks for the info!  I haven't touched this project in years, so it's mostly just up here on GitHub as a searchable reference for anybody else looking for a starting point for implementing file readers for these old file types (I've found my code floating in the OpenRA project, amongst others :smile: ).  I'll probably link to this issue from that source so that others can see your comment, but it's unlikely I'll actually fix the code.

**Comment by OmniBlade** [comment]
No problem, I did use your code as a reference when I drafted my own format40 encoder for WSA and TD Shp creators. If you are interested in taking a look I posted the code at http://cnc-comm.com/community/index.php?topic=4403.0.

**Comment by ultraq** [comment]
Doing some cleanup of older issues, am going to close this one now.  The WSA format seems to be well documented with up-to-date information in many more recent places I've looked, and there are a variety of tools that work with this format which take into account nuances like the one described above.

**Comment by ultraq** [comment]
Oh, I will implement the necessary changes.  Will make sure to tag the commit against this issue.
